"""Ingest closed-loop LLM-arm results → docs/CLOSED_LOOP_CROSS_MODEL_REPORT.md.

Reads results/embodied_llm_{deepseek,glm,kimi}.json (written by
run_embodied_llm.py via the embodied-llm.yml workflow) and renders a cross-model
report with the per-authority-arm table. Missing models are shown as "(pending)"
so this can be run now to produce the template and re-run to auto-fill once the
dispatched runs land. Read-only; no model calls; frozen baseline untouched.

Usage: python gen_closed_loop_report.py
"""
from __future__ import annotations

import json
import os

MODELS = [("deepseek", "DeepSeek deepseek-chat"),
          ("glm", "GLM glm-4-flash"),
          ("kimi", "Kimi moonshot-v1-8k")]
ARMS = ["planner", "a1", "ungated"]
ARM_LABEL = {"planner": "纯规划器", "a1": "A1-LLM+A*", "ungated": "无门控-LLM"}


def load(slug):
    path = f"results/embodied_llm_{slug}.json"
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def arm_row(d, arm):
    for a in d.get("arms", []):
        if a.get("arm") == arm:
            return a
    return None


def main():
    lines = [
        "# CLOSED_LOOP_CROSS_MODEL_REPORT.md — 闭环真实 LLM 臂（跨模型）",
        "",
        "Trajectory-level results of the 档 A closed-loop simulation with a REAL",
        "LLM as the L3 policy (`run_embodied_llm.py`), per authority arm. Same",
        "frozen grids as episodes; decisions live. Auto-generated by",
        "`gen_closed_loop_report.py` from `results/embodied_llm_<model>.json`.",
        "",
        "## 1. Per-arm metrics (success / SPL / collision / veto-load)",
        "",
        "| Model | arm | success | SPL | collision | veto | llm_calls | malformed |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    have_any = False
    headline = []
    for slug, label in MODELS:
        d = load(slug)
        if d is None:
            lines.append(f"| {label} | — | _(pending — dispatch embodied-llm.yml)_ | | | | | |")
            continue
        have_any = True
        calls = d.get("llm_calls", "?")
        malformed = d.get("malformed_decisions", "?")
        a1 = arm_row(d, "a1")
        ung = arm_row(d, "ungated")
        if a1 and ung:
            headline.append(
                f"{label}: A1 collision {a1['collision_rate']:.3f} (SPL {a1['spl']:.3f}) "
                f"vs ungated {ung['collision_rate']:.3f}")
        for arm in ARMS:
            a = arm_row(d, arm)
            if a is None:
                continue
            lines.append(
                f"| {label} | {ARM_LABEL[arm]} | {a['success_rate']:.3f} | "
                f"{a['spl']:.3f} | **{a['collision_rate']:.3f}** | "
                f"{a.get('veto_rate', 0):.3f} | {calls} | {malformed} |")

    lines += ["", "## 2. Headline"]
    if have_any:
        lines += [f"- {h}" for h in headline]
        lines += [
            "",
            "**Expected pattern (confirm against the rows above):** A1 holds the",
            "collision rate at 0.000 for every model (safety by construction), while",
            "ungated collides at the per-step unsafe rate compounded over the",
            "trajectory. Because a real LLM is more accurate than the greedy/random",
            "reference policies, its A1 SPL should sit well above the reference arms",
            "and approach the pure-planner upper bound — i.e. A1 keeps the LLM's",
            "competence where it helps while removing its danger.",
        ]
    else:
        lines += [
            "- _(No model results yet.)_ Dispatch **Embodied LLM Arm** "
            "(`embodied-llm.yml`) for deepseek / glm / kimi, download the artifacts",
            "  into `results/`, then re-run `python gen_closed_loop_report.py`.",
        ]
    lines += [
        "",
        "## 3. Thesis slot-in",
        "These numbers fill the in-progress real-LLM rows of 中文论文 §4.7 and the",
        "closed-loop contribution in §6. The reference-arm result (A1 collision 0 vs",
        "ungated 0.59/0.94) is already committed in `EMBODIED_RESULTS.md` / §4.7.",
    ]
    os.makedirs("docs", exist_ok=True)
    with open("docs/CLOSED_LOOP_CROSS_MODEL_REPORT.md", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote docs/CLOSED_LOOP_CROSS_MODEL_REPORT.md "
          f"({'with data' if have_any else 'TEMPLATE — pending runs'})")


if __name__ == "__main__":
    main()
